### ISSUE TITLE
[Feature Request] Global Icon Search

### ISSUE THREAD

**Issue by fundoozzz** [danimahardhika/candybar-library#1]
Within the Icon section where you can preview the icons included in the icon pack it would be great if the search is performed globally i.e. across all categories at the same time instead of searching the category currently being viewed. This is the feature most users request in order to find icons easily.
Thanks

**Comment by danimahardhika** [comment]
Added in release [**1.0.7**](https://github.com/danimahardhika/candybar-library/releases/tag/1.0.7)
