### ISSUE TITLE
Wrong requested icon count results in App crash

### ISSUE THREAD

**Issue by Steve2955** [danimahardhika/candybar-library#10]
When you select a few Apps, which you want to request and then spam(click very rapidly) one this may sometimes resolve in a wrong selected apps count in the toolbar(count is one to high). If you then click the FAB to send the request the app crashes. I tried this in the Sample App and in the Delta-Icon Pack, it worked on both. 

PS: Please don't ask me why somebody would do something like that.

**Comment by danimahardhika** [comment]
Fixed in release [**1.3.6**](https://github.com/danimahardhika/candybar-library/releases)
