### ISSUE TITLE
[Request] Support Microsoft Launcher

### ISSUE THREAD

**Issue by CodingFrieda** [danimahardhika/candybar-library#100]
Hi @danimahardhika,
what do you think of adding the [Microsoft Launcher](https://play.google.com/store/apps/details?id=com.microsoft.launcher) to the in-app **Apply** section and to the [list](https://github.com/danimahardhika/candybar-library/wiki/List-of-Supported-Launcher)? 
Thank you so much!

**Comment by danimahardhika** [comment]
Microsoft launcher doesn't support both direct apply or manual apply
