### ISSUE TITLE
Muzei issue (only using downloaded Walls)

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#101]
A user of mine reported an issue that activating "Only use downloaded Wallpapers" in the Muzei Options has no effect. I reproduced the issue on a device i had at hand, yet i'm not sure if it maybe has something to do with my device.

Thanks for your help :)

**Comment by danimahardhika** [comment]
Which version of CandyBar are you using?

**Comment by leifniem** [comment]
Issue was reported on 3.4.1

**Comment by danimahardhika** [comment]
There's some changes in muzei with latest version. I'll take a look into it, hopefully this options still possible. If not, I need to remove it.

**Comment by leifniem** [comment]
Alright, thank you :)

**Comment by danimahardhika** [comment]
Unfortunately latest version of muzei doesn't supports loading image from path, need to use the url, muzei will manage the cache. So this option will be removed.

**Comment by leifniem** [comment]
Alright, thanks for the info :)
