### ISSUE TITLE
Android Oreo only Force Close with icon requests

### ISSUE THREAD

**Issue by Primokorn** [danimahardhika/candybar-library#102]
Hi,
I received several feedbacks from users. It's an Oreo bug (100% of bug reports in the Play Store Dev Console).
Unfortunately I only run Nougat on my devices.

Here is the log:
`java.lang.NullPointerException:`
`at android.view.View$4.setValue (View.java:24453)`
`at android.view.View$4.setValue (View.java:24451)`
`at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue (PropertyValuesHolder.java:1379)`
`at android.animation.ObjectAnimator.animateValue (ObjectAnimator.java:990)`
`at android.animation.ValueAnimator.setCurrentFraction (ValueAnimator.java:654)`
`at android.animation.ValueAnimator.setCurrentPlayTime (ValueAnimator.java:617)`
`at android.animation.ValueAnimator.start (ValueAnimator.java:1046)`
`at android.animation.ValueAnimator.start (ValueAnimator.java:1065)`
`at android.animation.ObjectAnimator.start (ObjectAnimator.java:852)`
`at android.animation.ValueAnimator.startWithoutPulsing (ValueAnimator.java:1058)`
`at android.animation.AnimatorSet.handleAnimationEvents (AnimatorSet.java:1142)`
`at android.animation.AnimatorSet.doAnimationFrame (AnimatorSet.java:1046)`
`at android.animation.AnimationHandler.doAnimationFrame (AnimationHandler.java:146)`
`at android.animation.AnimationHandler.-wrap2 (Unknown Source)`
`at android.animation.AnimationHandler$1.doFrame (AnimationHandler.java:54)`
`at android.view.Choreographer$CallbackRecord.run (Choreographer.java:964)`
`at android.view.Choreographer.doCallbacks (Choreographer.java:778)`
`at android.view.Choreographer.doFrame (Choreographer.java:710)`
`at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:952)`
`at android.os.Handler.handleCallback (Handler.java:789)`
`at android.os.Handler.dispatchMessage (Handler.java:98)`
`at android.os.Looper.loop (Looper.java:164)`
`at android.app.ActivityThread.main (ActivityThread.java:6803)`
`at java.lang.reflect.Method.invoke (Native Method)`
`at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)`
`at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)`

Thank you!

**Comment by xorRisont** [comment]
Nexus 6P - Oreo (OPR5)
CandyBar library v3.4.1
All fine

**Comment by danimahardhika** [comment]
@Primokorn Make sure you are using latest release, also if you still got the crash report, check the app version and make sure it's the latest.

**Comment by Primokorn** [comment]
@danimahardhika I've just received a new email from a user.
He's using the latest version of my icon pack which is based on CandyBar v3.4.1.
As recommended I always clean the project before compiling.

**Comment by xorRisont** [comment]
@Primokorn did you edit the library? or you work only wiyh a sample project?

**Comment by danimahardhika** [comment]
@Primokorn The log doesn't show anything related to CandyBar. Probably this is just a random crash, like user close the app when there's a running process (loading or building icon request).

As @xorRisont said, the dashboard works fine on Android Oreo

**Comment by Primokorn** [comment]
@xorRisont I follow the [wiki](https://github.com/danimahardhika/candybar-library/wiki/How-to-Update) (by updating build.gradle as always).

@danimahardhika Okay then I'll ask them to send a full log. It may help to understand the force closes.

**Comment by Primokorn** [comment]
@danimahardhika I found a (unstable) AOSP rom to flash on my Nexus 5 to try my icon pack on Oreo.
Here is [a part of the log](https://osine.cozycloud.cc/public/hastebin/NkyAxeTd)
`com.osheden.raya` is the icon pack.

I can't post the log due to the instability of the ROM. I got about 4000 lines in 5s...

**Comment by xorRisont** [comment]
@Primokorn please try in Android Emulator

**Comment by Primokorn** [comment]
@xorRisont I've never tried the emulator but I'll try tomorrow and keep you informed.

**Comment by xorRisont** [comment]
@Primokorn 
@danimahardhika 
https://youtu.be/UdoZUBs5Urs

**Comment by xorRisont** [comment]
@Primokorn 
https://youtu.be/UdoZUBs5Urs
i can make video with all dashboard's functional

**Comment by Primokorn** [comment]
The emulated devices don't start on my computer (Manjaro Linux) so I can't try with an emulator...

**Comment by xorRisont** [comment]
@Primokorn ok. your iconpack don't start  on any device (8.0) or broke some function?

**Comment by Primokorn** [comment]
@xorRisont The dashboard force closes when opening the icon request tool.
I use Candybar for all my icon packs and only Raya force closes. I finally found a solution to get the emulator working and I tested other icon packs.

I have uploaded the full log. Maybe you can find something.
I tried to clean and rebuild the project. I don't know what to do now...

[log.txt](https://github.com/danimahardhika/candybar-library/files/1403951/log.txt)

**Comment by danimahardhika** [comment]
It seems like you are modifying the library and because the log shows there's a required resource that missing.

**Comment by Primokorn** [comment]
How could I do that?
I think I'll start from scratch by creating a brand new app/dashboard.

**Comment by Primokorn** [comment]
@danimahardhika So I created a new icon pack from scratch using v3.4.1 and I also have a force close with the icon request tool :-(
Is there anything I can do to solve this problem?

**Comment by danimahardhika** [comment]
@Primokorn What device are you using? And tell me what exactly are you doing? When the crash happened?

**Comment by Primokorn** [comment]
@danimahardhika I tried with this [ROM](https://forum.xda-developers.com/google-nexus-5/orig-development/aosp-oreo-8-0-0-nexus-5-t3664033) on my Nexus 5 and a Pixel (8.0 system image) with the Android Studio Emulator.

From the main screen of the dashboard, I select the **Icon Request** card then the app force closes.

**Comment by danimahardhika** [comment]
Tried on Nexus 6 and Pixel with Android Oreo everything works fine.

Make sure you have updated your Android SDK. Make sure to have latest version of android support repository and android support library.

Also make sure to put appfilter.xml inside xml folder.

**Comment by Primokorn** [comment]
I'll do but I launched the SDK manager so everything should be up to date.

Actually I think it could be caused by the config file (java folder).
I'm not at home but I'll try with the config file of a working icon pack.

**Comment by Primokorn** [comment]
@danimahardhika The problem was indeed with the file .../java/com/osheden/raya/applications/CandyBar.java

[diff](https://www.diffchecker.com/A5hJLowi)
On the left, the working config
On the right, the file that doesn't work on Oreo.

My computer is not powerful so I can't make many tests until I find the line that creates the error.

**Comment by danimahardhika** [comment]
I'll take a look into it

**Comment by aiocen** [comment]
Hey, I'm getting crash reports with a similar issue. The user is also running Oreo and the app crashes when icon request is pressed. I attached the crashlog, hope it can be useful.
[crashlog.txt](https://github.com/danimahardhika/candybar-library/files/1425454/crashlog.txt)

**Comment by danimahardhika** [comment]
@Primokorn @aiocen I can't find which part that causing this problem. Tried on emulator and my own device, everything works fine. Already tried using @Primokorn configuration also works fine. I really needs some help. It will be more helpful if you know about logcat.

**Comment by Primokorn** [comment]
@danimahardhika I have no device that runs Oreo. I'll try to install a stable build on my OnePlus 3T.
Emulator requires too much power to run.
What do you need in the log? The part where the crash happens, right?

**Comment by danimahardhika** [comment]
@Primokorn Yes, the current log posted here doesn't really help

**Comment by Primokorn** [comment]
@danimahardhika I'm finally on Oreo 8.1.0 and I tested a whole new config file for **CandyBar.java**.
No FC on my end so I think we can close this issue.
Maybe I made a mistake in my previous file.
