### ISSUE TITLE
Wrong appmap.xml builder

### ISSUE THREAD

**Issue by xorRisont** [danimahardhika/candybar-library#103]
In icon request mail (containing in *.zip) appmap.xml has wrong activity configuration. Needed _com.package.Activity_, but we have _com.package_.
Example:
auto builded string:
`<item class="com.tencent.mm" name="wechat" />`
Right string:
`<item class="com.tencent.mm.ui.LauncherUI" name="wechat" />`

Appmap using in Atom Launcher and configuration like "com.package" don't work

**Comment by danimahardhika** [comment]
That's correct. It should be **package name** not activity

**Comment by xorRisont** [comment]
@danimahardhika then why Atom launcher don't work (if i use only package name?), but if i add packega.Activity - icon works in Atom Launcher

**Comment by danimahardhika** [comment]
Sorry my bad, it should be the activity

**Comment by xorRisont** [comment]
@danimahardhika but if a chenge in RequestHelper.java:360
`"\t<item class=\"" + request.getPackageName() + "\" name=\"" +`
to
`"\t<item class=\"" + request.getActivity() + "\" name=\"" +`
i get format: **com.package/com.package.Activity** right?
