### ISSUE TITLE
Gradle script not compatible with gradle tools 3.0.0

### ISSUE THREAD

**Issue by Max-Patchs** [danimahardhika/candybar-library#104]
I deleted the lines and it worked, dose they effect the icon pack in anyway

![capkkture](https://user-images.githubusercontent.com/25152124/32116394-c28ac6c0-bb4a-11e7-90e5-c2fa4adae559.PNG)

**Comment by tfarina223** [comment]
I just updated and got the same problem
![screenshot 51](https://user-images.githubusercontent.com/31830092/32116886-59436b5c-bb1a-11e7-9a69-4f7fe623cfd6.png)

**Comment by Max-Patchs** [comment]
you just need to delete the lines and it should work, what I am asking is the lines what dose they effect in the app?

**Comment by danimahardhika** [comment]
https://github.com/danimahardhika/wallpaperboard/issues/97

There are a lot of changes in gradle tools 3.0.0, basically it's the **gradle tools** version not Android Studio.

It's recommended to downgrade gradle tools to 2.3.3 or 2.3.2 and stick with that until a new release. Open root build gradle, and you will see gradle tools version there, change 3.0.0 to 2.3.3 or 2.3.2.

If you really want to use gradle 3.0.0
Open project `build.gradle` then
Replace this
```gradle
android.applicationVariants.all { variant ->
    variant.outputs.each { output ->
        def file = output.outputFile
        def appName = parent.name
        def fileName = appName.replace(" ", "_") + "_v" + variant.versionName + ".apk"
        output.outputFile = new File(file.parent, fileName)
    }
}
```

**Edit:** with this
```gradle
android.applicationVariants.all { variant ->
    variant.outputs.all { output ->
        def appName = parent.name
        def fileName = appName.replace(" ", "_")
        outputFileName = "$fileName-v${variant.versionName}.apk"
    }
}
```

**Comment by tfarina223** [comment]
Works for me. Thanks man!

**Comment by Max-Patchs** [comment]
now when building a signed apk with new code its just say that its done but it doesn't generate any apk file, so I will have to go back to the old gradle 2.3.0

**Comment by danimahardhika** [comment]
Generated apk located inside release folder

**Comment by danimahardhika** [comment]
Check release [3.5.0-b1](https://github.com/danimahardhika/candybar-library/releases/tag/3.5.0-b1)
