### ISSUE TITLE
Unable to build with 3.5.0-b2 and Android Studio 3

### ISSUE THREAD

**Issue by Primokorn** [danimahardhika/candybar-library#107]
Hi
I've just updated to 3.5.0-b2 (import of the new template) and I have this error message when building my signed apk:
> Warning:Exception while processing task java.io.IOException: proguard.ParseException: Unknown option 'android.support.v7.graphics.**' in line 22 of file '/home/arnaud/Thèmes/Raya/app/proguard-rules.pro'
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

![as_1](https://user-images.githubusercontent.com/5938828/32396360-2987fccc-c0e5-11e7-9b05-1aca1983b643.png)
The 4 options of Support Repository are checked.
![as_2](https://user-images.githubusercontent.com/5938828/32396361-29c8e7be-c0e5-11e7-8604-1c09d3f7a5fc.png)
![as_3](https://user-images.githubusercontent.com/5938828/32396362-29f8cf60-c0e5-11e7-9cbc-2f814c2d6332.png)

*Android API 27* is partially installed. I don't know why. Can it explain the error?
Thank you.

**Comment by danimahardhika** [comment]
Open file `proguard-rules.pro` and follow this commit https://github.com/danimahardhika/candybar-sample/commit/9f3dd975a00a32e8396f55daaed2bec2e28a77e6

**Comment by Primokorn** [comment]
Problem solved, thanks for your support.
