### ISSUE TITLE
Unable to load InApp Purchase products

### ISSUE THREAD

**Issue by Primokorn** [danimahardhika/candybar-library#108]
Hi,
Not sure if you noticed [this post](https://plus.google.com/+H%C3%A9denOS/posts/GsM1aiatVSE) on G+. Anyway I think it's better to create an issue here.

So with 3.5.0-b2 and Android Studio 3.0, we can't use the premium requests (buy new ones).

Here is a full log:
[logcat_and_device_info.zip](https://github.com/danimahardhika/candybar-library/files/1443886/logcat_and_device_info.zip)
*Package name:* com.osheden.raya

**Comment by danimahardhika** [comment]
Just tested it, it's working just fine. Make sure to check your license key and product id. Also in app purchase won't works in debug mode, you need to generate signed apk first.

**Comment by Primokorn** [comment]
Yes I checked them. I even tried creating a new product ID.
APK was signed and pushed to my phone through adb.

I tested with another icon pack (before upgrading AS and Candybar) and the log shows:
> Account determined from library ownership - [....................]

now we get:
> Account determined from installer data - [....................]
