### ISSUE TITLE
SQLiteConnection object leaked

### ISSUE THREAD

**Issue by Primokorn** [danimahardhika/candybar-library#109]
Hi,

While reading a log I found this line:
`W/SQLiteConnectionPool(22043): A SQLiteConnection object for database '/data/user/0/com.osheden.raya/databases/candybar_database' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.`

What does it mean?
Thanks.

Candybar 3.5.0-b2

**Comment by danimahardhika** [comment]
That's just a logging, not an error.
