### ISSUE TITLE
[Suggestion] Support for promo codes

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#11]
Hello again,

as far as i understood promotional codes generated by the Developer Console need a special implementation to work. Would be a nice to have, but not a necessity.

Thanks again for this dashboard :)

**Comment by danimahardhika** [comment]
<p align="center"><img src="https://drive.google.com/uc?id=0B0f4ypHfNKm5aldraDJSNGVweU0" width="260" align="middle">

Choose Redeem to use promo code. I think it should works to for premium request, haven't tested it.
It's not controlled by dashboard, Google InApp Purchase control it.

**Comment by leifniem** [comment]
Oh, sorry :)
