### ISSUE TITLE
CM Launcher

### ISSUE THREAD

**Issue by OSHeden** [danimahardhika/candybar-library#110]
Hi, 
I have received a request from an user : could you support this launcher : https://play.google.com/store/apps/details?id=com.ksmobile.pro.launcher

Thank you.

**Comment by danimahardhika** [comment]
The launcher supports theme, but it's different with icon pack. The icon stored in assets folder. So it's not possible.

**Comment by OSHeden** [comment]
OK, thanks for your answer. I'll let him know.
