### ISSUE TITLE
Icons not auto-applying

### ISSUE THREAD

**Issue by alexcirco** [danimahardhika/candybar-library#115]
I installed this on 2 devices. Tried Nova and Solo both from Dashboard and from launcher's settings but the icons don't auto-apply (only manually).

I tripple-checked the files: 
**_appfilter, appmap, drawable, theme-resource_**  
Copied **_appfilter, appmap_** in **assets** as well).

What am i missing or doing wrong?

**Comment by Primokorn** [comment]
What did you install exactly? The Candybar sample?
Did you try one of these icon packs: https://github.com/danimahardhika/candybar-library#icon-pack-using-candybar
If an icon pack doesn't support icon masking you have to install supported apps (which can be found in the appfilter.xml file => for Nova at least).
