### ISSUE TITLE
Unsupported Launcher for Candy Bar

### ISSUE THREAD

**Issue by SauravKarki** [danimahardhika/candybar-library#117]
Hey there,

First of all I would like to thank you for creating such an awesome library(Candy Bar). 
We have around 8 to 10 products that uses your library in which Icon Pack - Paper shaped original icons, Tiny Icon Pack  are the ones
We are facing some issue on some of the launchers which are listed as supported in your library such as Solo Launcher, Go Launcher but are not supported in our Icon Pack. While Applying from the dashboard the icons only get refreshed but doesn't change.
Any suggestion on this would be highly appreciable.
Seeing forward to hear from you.

Regards,
Saurav Karki
Kandara Tech

**Comment by danimahardhika** [comment]
First, dashboard and icon pack compatibility is 2 different thing. Regarding the icon pack compatibility, I already include the basic sample. If you think you need to modify it, you can modify it.

The things you asked is about icon pack compatibility. Make sure to check all xml inside xml and assets folder. Also make sure to put your appfilter.xml and drawable.xml both in assets and xml folder.

Also it's better to ask something related to the icon pack in community. Open new issue only if you have the problem with the dashboard.

**Comment by SauravKarki** [comment]
Sure,
Thanks for the quick response
