### ISSUE TITLE
Customize "About Header image" ratio [Request]

### ISSUE THREAD

**Issue by utsavmadaan1995** [danimahardhika/candybar-library#119]
Please allow customization of About Header image ratio (default 16:7 in fragment_about_item_header) as i think height is very low (screenshot attached) and i found no possible way of doing it (marked private) except to use library as a module itself which is not ideal.
![screenshot_20171210-170821](https://user-images.githubusercontent.com/26673311/33804522-da554c4a-ddcc-11e7-867f-997aad4e70e1.png)

**Comment by danimahardhika** [comment]
Instead the value, you also able to override the layout. Copy `fragment_about_item_header.xml` layout to your project and change height and width ratio.

**Comment by utsavmadaan1995** [comment]
Oo teri..i didn't knew that we can override resource of any included library by including same resource in project and modifying it..i thought i have to include it as module dependancy and than modify the resource file..thanks a ton...but does that mean accidently i can override things like string, color, drawable, etc of libraries..anywayz thanku
