### ISSUE TITLE
Icon Request Issue

### ISSUE THREAD

**Issue by omekurnia** [danimahardhika/candybar-library#125]
I haven't publish my icon pack on play store yet and currently testing on some of my friends. I found an issue on icon request section. They already requested icons but it never arrived on my email, on the other hand i can flawlessly send icon request on my phone and it arrived as soon as i clicked send.

I don't know if this was about unsigned apk or not. But the one in my phone is installed via run on android studio and on my friend is via build unsigned apk.

Thanks for your response 😊

**Comment by danimahardhika** [comment]
When you press the send button, the dashboard will ask tho choose email client. After that email client will handle the email. So, this is not related at all with the dashboard.

**Comment by omekurnia** [comment]
Thanks, you are right. They checked on their outbox amd apparently the email still sending. I think the issue is on gmail.
