### ISSUE TITLE
Home image shows instead of some icons in icons Tray

### ISSUE THREAD

**Issue by strangerweather** [danimahardhika/candybar-library#126]
![example](https://user-images.githubusercontent.com/6605897/35008417-530572ac-faf4-11e7-92e9-f9a95d90ea90.png)
I put a jpeg home image in drawable. Now this image shows in place of some icons in my icons tray. Is it a bug?

**Comment by danimahardhika** [comment]
No, because that image included in drawable.xml

**Comment by strangerweather** [comment]
So where do I need to put home_image? The instructions say to put it in drawable. :)

**Comment by danimahardhika** [comment]
Just remove the image from drawable.xml

**Comment by omekurnia** [comment]
Put it in your nodpi folder but don't write the name on drawable.xml. You just need to write its name on dashboard_configuration.xml at home_image.

**Comment by strangerweather** [comment]
Wait guys, the image is NOT included in drawable.xml, that's the point. It is still showing in my icons trays instead of several icons.

**Comment by danimahardhika** [comment]
Which icon list? Icon list inside the dashboard or Icon Picker from launcher?

**Comment by strangerweather** [comment]
Hi, icon list inside the dashboard.

**Comment by danimahardhika** [comment]
Check your drawable.xml, dashboard only displaying icons which included in drawable.xml

**Comment by strangerweather** [comment]
I think it's because I called my home image "home_image". It must have caused a conflict. Now I have changed the name the problem is gone. I'll take advantage to thank you for all your work. It's really appreciated.
