### ISSUE TITLE
Candybar crash report: FC when opening the dashboard

### ISSUE THREAD

**Issue by Primokorn** [danimahardhika/candybar-library#128]
Hi,

My icon pack Trium has been downloaded by many users. It seems that the dashboard force closes for one person when opening the app.

Here is the log sent by the user.
[crashlog.txt](https://github.com/danimahardhika/candybar-library/files/1665018/crashlog.txt)

I have nothing in the Google dev console yet. Did you already receive similar reports?

**Comment by danimahardhika** [comment]
The crash log show missing xml file, but the file should come from the Android SDK. If it missing, then there must be something wrong with the OS, the ROM.

**Comment by Primokorn** [comment]
OK then I can close. Thanks for the reply.
