### ISSUE TITLE
Icons Fragment Not showing icons?

### ISSUE THREAD

**Issue by chnouman** [danimahardhika/candybar-library#132]
i have run this project on my studio and everything works fine but when i click on icon menu button it shows only empty tab with out name etc and no data in viewpager.
Can you please help me how to insert data into it?

**Comment by danimahardhika** [comment]
Fill your `drawable.xml` with your icon list

**Comment by chnouman** [comment]
thanks alot and sorry for my stupid question.

**Comment by chnouman** [comment]
@danimahardhika  sorry but i think i don't have idea how to add items in drawable.xml file. and is it also add new tab in icons fragment?

**Comment by danimahardhika** [comment]
Yes. That's related to Icon Pack stuff, if you don't know that, that means you don't know how to create an icon pack. Ask in community instead.

**Comment by chnouman** [comment]
i think in previous version we have some tabs and icons already in iconsBaseFragment isn't it/

**Comment by danimahardhika** [comment]
That previous version is a long time ago

**Comment by chnouman** [comment]
i figured out how it is fetching icons can you please help me how it is creating different tabs?

**Comment by danimahardhika** [comment]
Like I said before, that's related to Icon Pack stuff, not dashboard stuff.
You need to create `drawable.xml` to list your icons for Launcher Icon
Picker (like Nova, Apex, etc)

**Comment by chnouman** [comment]
ok dear thanks for your time.
