### ISSUE TITLE
Removing 512 x 512 pixels icon dimention square from dashboard

### ISSUE THREAD

**Issue by ghost** [danimahardhika/candybar-library#139]
There is a panel that says "512 x 512 pixels icon dimention" in the main dashboard. Is there a way to remove it?

[![20180305_144134.jpg](https://s18.postimg.org/rp0lu06eh/20180305_144134.jpg)](https://postimg.org/image/x0fiepsh1/)

**Comment by danimahardhika** [comment]
No you can't

**Comment by daVinci13** [comment]
@JustMeErazem Yes you can, send me an email.

**Comment by walrus543** [comment]
@daVinci13 What about sharing the information publicly?
