### ISSUE TITLE
Propose new logo

### ISSUE THREAD

**Issue by anaufalm** [danimahardhika/candybar-library#144]
Hello, I want to contribute to this awesome project, and I have a new logo design for you, if you allowed I will send to you :)

**Comment by xorRisont** [comment]
@anaufalm Show it to all! =)

**Comment by anaufalm** [comment]
Deleted.

**Comment by yeyebbc** [comment]
@anaufalm Hi, great work. I'm also a graphic designer.

Would you mind explain it, like the design story of it? 
I think the bar graph behind the candy means dashboard, does it?

It is a great logo, but not very suitable for an icon, for the complexity of graph components is a bit too high for an icon to contain. Hmmm....maybe it wasn't designed for icon display at the beginning....

Thanks for sharing your great work! (●'◡'●)

**Comment by kundan333** [comment]
Awesome work @anaufalm

**Comment by anaufalm** [comment]
Thanks for the comment @antoniacrespoa2.

The concept of this logo is to combine candy icon and bar graph. So they become Candybar.
I can remove the graph bar if it becomes annoying.

**Comment by anaufalm** [comment]
Deleted.

**Comment by anaufalm** [comment]
No comment? @antoniacrespoa2 ?

**Comment by walrus543** [comment]
@anaufalm No need for a new logo if the development of the dashboard is suspended (sorry).

**Comment by anaufalm** [comment]
Okay, thank you. :)
