### ISSUE TITLE
[Question] How can I disable Muzei, Share and Rate & Review parts?

### ISSUE THREAD

**Issue by DanyGee** [danimahardhika/candybar-library#147]
First of all, thank you for a solid piece of work! 🥇 
The launcher is fast, smooth and configurable, and the code clean as a whistle 👍 

Before I publish my iconpack I would like to disable Muzei, Share app feature and Rate & Review for my beta testers 👶 

Can you tell me which part of the code to modify without braking anything? 😉

**Comment by ghost** [comment]
I tried to remove anything about muzei inside the project on Android Studio and still appears on the dashboard , also Google Play Developer Console refuse the app , please watch the photo attached.
![20182905_131329_pdt](https://user-images.githubusercontent.com/16510259/40805481-ac769f5c-651e-11e8-8ca5-24acea71618e.png)

**Comment by daVinci13** [comment]
@DanyGee  @lohigno  contact me via email. Mine is on my profile. I'll explain you how to remove muzei and modify the UI.

**Comment by DanyGee** [comment]
> @DanyGee @lohigno contact me via email. Mine is on my profile. I'll explain you how to remove muzei and modify the UI.

@daVinci13 What is stopping you from sharing that secret here, for others too?

**Comment by angelgavipo** [comment]
Good morning, I have the same problem, Google has disabled my application for violating advertising policies and has sent me this image.
I'll thank you for helping me to disable the muzzei of the dashboard. Thank you

**Comment by ghost** [comment]
@DanyGee @angelgavipo I'll give you a help with Muzei that was the only one I've changed so far.

If you are using **candybar-sample**, download the [fragment_home_item_wallpapers.xml](https://github.com/danimahardhika/candybar-library/blob/master/core/src/main/res/layout/fragment_home_item_wallpapers.xml) file into the `/app/src/main/res/layout/` folder.

Then edit the file. Inside it there is a \<TextView> with `android:id="@+id/muzei"` and above it there is a \<View>. Add the parameter `android:visibility="gone"` in both.
I have not tested with others but I believe they can follow the same idea.

Cheers! :slightly_smiling_face:

**Comment by ghost** [comment]
@DanyGee 
For the **share** and **rate** buttons you need to use the same parameter `android:visibility="gone"`.

You will need to edit the file [fragment_home_item_header.xml](https://github.com/danimahardhika/candybar-library/blob/master/core/src/main/res/layout/fragment_home_item_header.xml) or [fragment_home_item_header_alt.xml](https://github.com/danimahardhika/candybar-library/blob/master/core/src/main/res/layout/fragment_home_item_header_alt.xml).

The difference between them is that the **_alt** version corresponds to the app home screen with the header expanded to the edge of the screen while the **non _alt** corresponds to the app home screen with the header inside the card.
Download the file into the `/app/src/main/res/layout/` folder.

There are two **\<LinearLayout>** within the file. Add parameter `android:visibility="gone"` within the second **\<LinearLayout>**.

That's it.

**Comment by DanyGee** [comment]
@mluizvitor 
Thanks a bunch!
I can confirm your solution works 100%.
![bitmoji](https://render.bitstrips.com/v2/cpanel/f5f350c4-9252-4cb3-a6f0-d3990389fc90-fe85af63-ad51-4198-8b90-cb1af6ce89fd-v1.png?transparent=1&palette=1&width=246)
