### ISSUE TITLE
[Question] How to set a Dynamic Calendar

### ISSUE THREAD

**Issue by djdoge** [danimahardhika/candybar-library#149]
**Hi,**
I've made 31 Calendar icons (one for each day) and I'm wondering (if it's possible) how I can set the icons to automatically change day by day?

I've googled around and found this post: [DynamicCalendarExample](https://github.com/teslacoil/Example_NovaTheme/blob/master/DynamicCalendarIconAPI.md)
but I still don't 100% follow. Thank you for the help!

**Comment by yeyebbc** [comment]
The post explained well in detail. Just like this:

`<calendar component="ComponentInfo{com.google.android.calendar/com.android.calendar.LaunchActivity}" prefix="google_calendar_"/>`

You should name your 31 icons with the prefix of "google_calendar_", for example:
Day 1's name is "google_calendar_1.png"
Day 2's name is "google_calendar_2.png"
......

Like this, don't forget to add static icon for launchers that doesn't support dynamic calendar
<img width="595" alt="snipaste_2018-05-09_10-44-33" src="https://user-images.githubusercontent.com/19569343/39793011-07613018-5376-11e8-91cf-1774232a3301.png">

**Comment by djdoge** [comment]
I've added "<calendar component="ComponentInfo{com.google.android.calendar/com.android.calendar.LaunchActivity}" prefix="google_calendar_"/>" to appfilter.xml like this:
<img width="933" alt="screen shot 2018-05-09 at 09 08 23" src="https://user-images.githubusercontent.com/24941577/39800615-adcaf226-5368-11e8-84d7-d70678929874.png">

And I wasn't 100% sure if I had to add "...efix="google_calendar_1"/>", "...efix="google_calendar_2"/>" etc. 

I've added the icons but it still doesn't work :(
<img width="177" alt="screen shot 2018-05-09 at 09 11 17" src="https://user-images.githubusercontent.com/24941577/39800709-fbcaef58-5368-11e8-902a-40605e43a7bd.png">

(I'm new to all of this as you might see haha)

**Comment by yeyebbc** [comment]
Hey you only need to use one line of code.
Only this line, 
`<calendar component="ComponentInfo{com.google.android.calendar/com.android.calendar.LaunchActivity}" prefix="google_calendar_"/>`

**Comment by djdoge** [comment]
Hello again! 

Do I need to edit in AndroidManifest.xml or is it enough that I add <calendar component="ComponentInfo{com.google.android.calendar/com.android.calendar.LaunchActivity}" prefix="google_calendar_"/> to appfilter and the icons to drawable with the names "google_calednar_x"

Thank you!!

**Comment by yeyebbc** [comment]
The CandyBar Dashboard support dynamic calendar icons by default, no need to edit AndrfoidManifest.xml.

**Comment by djdoge** [comment]
Huh.. I must be doing something wrong then :( Still isn't working

**Comment by yeyebbc** [comment]
Oh, no need for this "google_calendar_.png", started them from "google_calendar_1.png"

**Comment by benneb1020301** [comment]
Is there any way to make 2 dynamic calendars for one app ?
When I add 2 for the same app it's just uses the second one
