### ISSUE TITLE
[Help wanted] Customizing dashboard colors and creating app

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#2]
It is kinda unclear to me how to modify the dashboards files and go on to create the app itself. Maybe this would be something to add to the wiki. So far it really has been a charm to set up!

**Comment by danimahardhika** [comment]
Sorry, I'll edit it later and make it more simple
`dashboard_configurations.xml` &#8594; **Most** configurations goes here
`dashboard_icons.xml` &#8594; All of your icons goes here (newly added, apps, games, etc)
`License.java` &#8594; You need to see this only if you enable of the three **License Checker**, **Donation** or **Premium Request**
`changelog.xml` &#8594; Your changelog goes here
`colors.xml` &#8594; Dashboard color
