### ISSUE TITLE
Splash Screen & Home Screen Header

### ISSUE THREAD

**Issue by Technologx** [danimahardhika/candybar-library#20]
What would the splash screen image size be if it was just a text image instead of a icon? Also what is the home screen header image dimensions?

**Comment by danimahardhika** [comment]
Splash screen logo designed for icon, default size is `96 x 96 dp` (square), so your icon at least should have `256 x 256 pixels`. I'm using image with dimensions `1422 x 960 pixels` for home image.

**Comment by Technologx** [comment]
Thank you also I submitted 2 pull requests on the sample.

**Comment by Technologx** [comment]
I tried those dimensions the splash is to small &amp; the homepage header is to big. I've tried several different sizes &amp; can't seem to find the right size.

**Comment by danimahardhika** [comment]
@Technologx Splash screen logo wont increase or reduce even if you increase or decrease logo dimensions. What are you trying to achieve?

**Comment by Technologx** [comment]
I just want to have a text image file since I really can't have actual text.

**Comment by danimahardhika** [comment]
@Technologx It's not designed that way, hmmm

**Comment by cueapps** [comment]
Splash screen logo looks very small, anyway to adjust this?

**Comment by danimahardhika** [comment]
@cueapps 
For non tablet, copy this line to dimens.xml inside values folder
```xml
<dimen name="splash_screen_logo">96dp</dimen>
```

For tablet, copy this line to dimens.xml inside values-sw600dp
```xml
<dimen name="splash_screen_logo">114dp</dimen>
```

Adjust the size depending on your needs, **but this is not recommended**
