### ISSUE TITLE
Different quality when wallpaper applied from dashboard and gallery (downloaded first)

### ISSUE THREAD

**Issue by danimahardhika** [danimahardhika/candybar-library#23]
Applied from dashboard (left), applied from gallery (right)
<img src="https://drive.google.com/uc?id=0B0f4ypHfNKm5aUhGcWtXdzROdGs" width="300px"/> <img src="https://drive.google.com/uc?id=0B0f4ypHfNKm5OEFzSkZ1NlJzeHc" width="300px"/>

**Comment by Technologx** [comment]
I think the picture quality from the dashboard looks slightly better
