### ISSUE TITLE
Icon request section not hidden properly

### ISSUE THREAD

**Issue by danimahardhika** [danimahardhika/candybar-library#28]
- Icon request section not hidden even when both icon request and premium request disabled.
- Icon request section not hidden when lucky patcher installed (only for condition: premium request enabled and icon request disabled)

**Comment by fundoozzz** [comment]
The second point does not stand true, icon request section hidden if premium request enabled and icon request disabled. The only issue is when both icon request and premium icon requests are disabled, the icon request section does not gets hidden.
![image](https://cloud.githubusercontent.com/assets/1597407/23446560/8ec45420-fe6a-11e6-8563-e3d23226c678.png)

![](https://lh3.googleusercontent.com/-dyHF5KirjMM/WLWScinrRaI/AAAAAAAAHPs/61zOApiNMY49WFbnkj1iM_05YhdpK-WiACL0B/h402/Dashboard%2BIcon%2BRequest%2BResult.jpg)
