### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#3]
Couldn't figure them out myself, but it's a minor issue.

Keep up the fantastic work!

**Comment by danimahardhika** [comment]
Just something like this
* `abc` &#8594; `Abc`
* `abc_abc` &#8594; `Abc abc`

**Comment by danimahardhika** [comment]
After considering about this, I think this is not necessary. I'm not going to add naming convention. I just want to make it simple. All underline `_` will be replaced with space ` `.
