### ISSUE TITLE
[Suggestion] Bug Report Message

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#32]
Since i've lately been getting a lot of Bug Report Mails, which include basically no useful information without an description of the error, i'd like to suggest an additional message Dialog when Reporting Bugs, to make sure people do not use the feature to troll.

Would such a feature be hard to add?

**Comment by danimahardhika** [comment]
Report Bugs actually used to report broken activity, like you include the icon but add wrong activity or mistyped it.

I'm thinking to add dialog to choose what kind of bug that user want to report, like
- Icon included inside icons preview, but the actual icon not change
- Another one
- etc

**Comment by leifniem** [comment]
Sounds great :)

**Comment by danimahardhika** [comment]
@leifniem Since I have prepared to release 2.0.5, I will add this options in next update, sorry...

**Comment by xorRisont** [comment]
@danimahardhika 2.0.5 will be release today?))

**Comment by danimahardhika** [comment]
@leifniem I added a dialog before user send report bugs in release [3.0.2](https://github.com/danimahardhika/candybar-library/releases/tag/3.0.2)

<img src="https://drive.google.com/uc?id=0B0f4ypHfNKm5LUNRWXJudWhhSFE" width="220"/>

**Comment by leifniem** [comment]
Fantastic! You're the man!
