### ISSUE TITLE
Go Launcher Z support

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#33]
I got a few reports from users having trouble with Go Launcher.
May this be due to an overhaul (the "Z"-suffix of the name is new to me) ? That would explain changed API's and the issue itself.

Thanks for taking a look :)

**Comment by danimahardhika** [comment]
@leifniem What kind of trouble? Please give more explanation

**Comment by leifniem** [comment]
The icons not applying when choosing the icon pack. I tested it on an emulator and when choosing the pack itself it does not apply, in contrast to when you edit single icons manually, those did somehow work.

**Comment by danimahardhika** [comment]
I know Go Launcher Ex, haven't heard about Go Launcher Z. If that refers to this https://play.google.com/store/apps/details?id=com.gau.go.launcherex, check here https://github.com/danimahardhika/candybar-sample/tree/master/app/src/main/assets. Make sure you include all of them inside assets folder

**Comment by leifniem** [comment]
I actually don't even care about GO Launcher since it's commercial bullshit, just wanted to document this because of the issue. I did include the given files, so i guess it's a launcher issue.

I think we can close this for now and if this issue gets more present give it attention if needed.

**Comment by danimahardhika** [comment]
@leifniem Let me check first

**Comment by danimahardhika** [comment]
@leifniem Tried using [Minimale Icon Pack](https://play.google.com/store/apps/details?id=com.mowmo.minimale), icon applied with both manual apply from launcher settings and direct apply from dashboard. Only some default app icon (comes with GO Launcher Z) on homescreen not changed, like dialer, themes, effect, etc. But apps icon on app drawer changed.

**Comment by leifniem** [comment]
That's odd. Thanks for your help, i guess I'll need to look at it closely.

**Comment by danimahardhika** [comment]
Make sure to check this again https://github.com/danimahardhika/candybar-sample/tree/master/app/src/main/assets

I added new XML there

**Comment by leifniem** [comment]
Will do so :) Thanks for your help!
