### ISSUE TITLE
Requests restore after uninstall

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#40]
A user told me purchased 10 premium requests, made 8 requests, uninstalled the app and reinstalled it and had 10 requests again.

Can't confirm it myself since i do not have a second google account, but can hand out promo codes to test this.

**Comment by danimahardhika** [comment]
There's no way to tell how many premium request left after reinstall unless you have your own online database to store that. Google InApp Billing only store which product id that still owned.

**Comment by leifniem** [comment]
I see. Thanks for the info :)
