### ISSUE TITLE
[Suggestion] Direct apply for Evie

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#41]
Had a lot of complains like "1 star because no evie support" (i know it has) but since there is no direct apply people tend to think it doesn't work.

Mailed the Evie team about intent filters but got no reply, so with no know-how i don't know if i can contribute anything :/

**Comment by danimahardhika** [comment]
At the moment Evie launcher doesn't support both direct and manual apply

**Comment by danimahardhika** [comment]
Evie launcher added to apply section (manual apply) on release [**3.1.0**](https://github.com/danimahardhika/candybar-library/releases/tag/3.1.0)
