### ISSUE TITLE
Search with spaces

### ISSUE THREAD

**Issue by mattcorner** [danimahardhika/candybar-library#45]
When using a keyboard that autocompletes and adds a space to the end of a word the search function cannot find apps that exist. I would suggest that search ignores trailing spaces when a character does not follow.

**Comment by danimahardhika** [comment]
Autocomplete should be disabled when using search by default.  I don't know about others keyboard, I'm using Gboard and autocomplete is disabled.

Ignore trailing space will make search result not accurate.

**Comment by mattcorner** [comment]
Using Fleksy here. 

I'd argue that it doesn't reduce search accuracy but actually benefits it. Not including a trailing space in search results is common practice in many other apps.

**Comment by danimahardhika** [comment]
I'll do some test first

**Comment by danimahardhika** [comment]
Check release [**3.1.2**](https://github.com/danimahardhika/candybar-library/releases/tag/3.1.2)
