### ISSUE TITLE
Widget Preview & Menu Items

### ISSUE THREAD

**Issue by Technologx** [danimahardhika/candybar-library#47]
Is there no in app widget preview for this dashboard? Also how do I go about adding extra stuff to the menu like a area for social links?

**Comment by danimahardhika** [comment]
CandyBar doesn't support any 3rd party widget app. If you want to edit, you need to figure it out by yourself.

**Comment by Technologx** [comment]
Can you not implement widgets into the dashboard, a lot of icon pack designers like having that feature. With yours not having it it's kind of boring no offense. It's a very nice dashboard though the best I've seen. I just really think you need to implement 3rd party widget stuff for Zooper & Kustom.

**Comment by Technologx** [comment]
Also can you not tell me what file I need to edit to add to the side menu?

**Comment by danimahardhika** [comment]
- `menu_navigation_view.xml`
- `CandyBarMainActivity.java`

**Comment by SanchithHegde** [comment]
@Technologx Were you able to implement the widget support?

Which file should I edit to implement the widget previews?

**Comment by Technologx** [comment]
@SanchithHegde No because I have no idea how to go about doing it.

**Comment by SanchithHegde** [comment]
@Technologx Oh okay. Thank you!

**Comment by SanchithHegde** [comment]
I have asked many people to help me, but none were able to. Dani sir, please add widget support. I'm unable to do it by myself. At least [Kustom support](https://bitbucket.org/frankmonza/kustomapi) would be good enough.

Than you ahead of time!

**Comment by daVinci13** [comment]
I tried to add and remove items on side menu, but no changes were made in layout. WTF?
