### ISSUE TITLE
Adding Launchers to List

### ISSUE THREAD

**Issue by Technologx** [danimahardhika/candybar-library#48]
How can I add launcher support to the apply list myself?

**Comment by danimahardhika** [comment]
Take a look ibside:
- `dashboard_launchers.xml`
- `LauncherHelper.java`
Just follow current format

**Comment by Technologx** [comment]
So is there any launcher code I need in particular?

**Comment by danimahardhika** [comment]
Yes, you need to find out if the launcher you want to add supports direct apply or not.

**Comment by dalight13** [comment]
Is there any way I can modify LauncherHelper.java? If so how? Do I have to import library into my app or can I just add a LauncherHelper.java class into my own app?

I'm trying to add BlackBerry Launcher : https://play.google.com/store/apps/details?id=com.blackberry.blackberrylauncher

I looked into LauncherHelper.java and found out that it works perfectly with "applyManual", If I can't modify it is there any way you could add it please?

I tested my Icon Packs with the BlackBerry Launcher and they work perfectly

Thank you in advance

daLight

**Comment by danimahardhika** [comment]
@dalight13 You should open a new issue instead. Blackberry launcher doesn't support direct or manual apply from the dashboard. The only way to apply icon pack is go to settings and apply icon pack from there.

**Comment by atanusanyal** [comment]
there is no dashboard_launchers.xml or LauncherHelper.java file !!!

**Comment by atanusanyal** [comment]
> Take a look ibside:
> 
> * `dashboard_launchers.xml`
> * `LauncherHelper.java`
> 
> Just follow current format

there is no dashboard_launchers.xml or LauncherHelper.java file !!!
