### ISSUE TITLE
Option to show number of icons

### ISSUE THREAD

**Issue by mddanishansari** [danimahardhika/candybar-library#49]
You may add an option to show number of icons in each category of icons in the tab. 
User may enable or disable this option from `dashboard_configuration.xml`

For example:- System(100), Games(72) etc.

**Comment by danimahardhika** [comment]
It was included, but the text for each category is very long and doesn't looks good, decided to remove it. I'll considering to add it back as an option.

**Comment by mddanishansari** [comment]
Looking forward for it

**Comment by Technologx** [comment]
I like the idea honestly

**Comment by Nicque** [comment]
If enable & disable options are there then it will a good addition once again!! 
I remember Dani had it in older versions of dashboard.

**Comment by danimahardhika** [comment]
Check here https://github.com/danimahardhika/candybar-library/wiki/Dashboard-Configuration
