### ISSUE TITLE
Enable Premium Icon Request Only

### ISSUE THREAD

**Issue by fundoozzz** [danimahardhika/candybar-library#5]
For a free icon pack, the daily number of downloads are over 1000 & if every user sends atleast 5 icon request, it will amount to 5000 icon request daily which is not possible to fulfill.
Instead there are users who are willing to make premium request to get their icons done in a free icon pack.

Issue :- 

If I disable Icon request but enable premium icon request, the icon request option disappears form the the side drawer. There should be an option to enable just the premium icon requests for Free icon packs.

**Comment by danimahardhika** [comment]
1. `enable_icon_request` &#8594; true
2. `enable_premium_request` &#8594; true
3. `enable_icon_request_limit` &#8594; true
4. `icon_request_limit` &#8594; 0
5. `reset_icon_request_limit` &#8594; false

**Comment by fundoozzz** [comment]
After doing the above, the UI does not remain intuitive.  At first it looks like Free Icon requests are allowed.
But when you click on the send button, it shows the following popup "You only able to make 0 requests with Regular Request. You can buy Premium Request to request more icons. You have requested 0 icons"

**Comment by danimahardhika** [comment]
Actually never think such condition could happen. I will considering about this for future update. You can take a look inside `dashboard_strings.xml`, you will found the message there. For now you can change the text showed in dialog. You should not remove the `<string>`, if you don't need one of them, just set to empty `<string ></string>`. It's hard to explain here, hope you understand.

**Comment by fundoozzz** [comment]
Yes, it's easy to edit the strings & make it usable for now so no issues, take your time.

**Comment by danimahardhika** [comment]
Fixed in release [**1.5.0**](https://github.com/danimahardhika/candybar-library/releases/tag/1.5.0)
