### ISSUE TITLE
Option to allow/not-allow theme change

### ISSUE THREAD

**Issue by mddanishansari** [danimahardhika/candybar-library#51]
You may add an option to allow or not allow theme change irrespective of it's default state(light/dark).

This must be added in `dashboard_configuration.xml` as a boolean.

If disabled must hide from `Settings `fragment

**Comment by danimahardhika** [comment]
No, this is not needed. I won't add it.

**Comment by danimahardhika** [comment]
Check here https://github.com/danimahardhika/candybar-library/wiki/Dashboard-Configuration
