### ISSUE TITLE
Admob Banner ad crashes app on startup

### ISSUE THREAD

**Issue by RonaldD7** [danimahardhika/candybar-library#52]
Interstitial ads work fine however ‘Banner ads’ crash the app on startup no errors in Android Studio.

**Comment by danimahardhika** [comment]
Forgot to say, please include the logcat

**Comment by RonaldD7** [comment]
ok cool will add that in a bit

**Comment by RonaldD7** [comment]
[logcat.txt](https://github.com/danimahardhika/candybar-library/files/1001159/logcat.txt)

**Comment by danimahardhika** [comment]
Open `CandyBarApplication.java`, disable the crash report

Change these line
```java
mHandler = Thread.getDefaultUncaughtExceptionHandler();
Thread.setDefaultUncaughtExceptionHandler(this::handleUncaughtException);
```

To
```java
mHandler = Thread.getDefaultUncaughtExceptionHandler();
Thread.setDefaultUncaughtExceptionHandler(this::handleUncaughtException);
```

After that try to run the app and see the logcat again

**Comment by RonaldD7** [comment]
Splash screen showed for a second then the app crashed.
[logcat2.txt](https://github.com/danimahardhika/candybar-library/files/1001385/logcat2.txt)

**Comment by danimahardhika** [comment]
The logcat is the same with first one

**Comment by RonaldD7** [comment]
Rebuild and cleaned project 
[logcat3.txt](https://github.com/danimahardhika/candybar-library/files/1001455/logcat3.txt)

**Comment by danimahardhika** [comment]
**Open [`CandyBarApplication.java`](https://github.com/danimahardhika/candybar-library/blob/master/core/src/main/java/com/dm/material/dashboard/candybar/applications/CandyBarApplication.java), disable the crash report**

Change these line
```java
mHandler = Thread.getDefaultUncaughtExceptionHandler();
Thread.setDefaultUncaughtExceptionHandler(this::handleUncaughtException);
```

To
```java
//mHandler = Thread.getDefaultUncaughtExceptionHandler();
//Thread.setDefaultUncaughtExceptionHandler(this::handleUncaughtException);
```

After that try to run the app and see the logcat again

**Comment by RonaldD7** [comment]
I have unless i'm doing something wrong cause i'm new to this, here's a screenshot if it may help.
![capture](https://cloud.githubusercontent.com/assets/28706783/26065013/edab999a-3992-11e7-84a7-3fb882035e42.PNG)

**Comment by RonaldD7** [comment]
Hey Dani! its cool will just have to do with interstitial ads for now thanks for trying to help really appreciated, if possible in your feature releases maybe implement Admob (interstitial & banner ads) as an option THANK YOU.

**Comment by danimahardhika** [comment]
That's correct. After you disabled the crash report you will be able to see correct logcat why your app crashed.

I will *never* add an option to disable or enable ads.
