### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by chnouman** [danimahardhika/candybar-library#53]
Kindly help me i'm new to android help me in use this template.

**Comment by danimahardhika** [comment]
If you already familiar with Icon Pack, then you're good to go
1. Open [Wiki Site](https://github.com/danimahardhika/candybar-library/wiki)
2. [Setup](https://github.com/danimahardhika/candybar-library/wiki/Setup), make sure to download sample project from [here](https://github.com/danimahardhika/candybar-sample).
3. Do customization
4. Add your icons, fill `appfilter.xml`, `drawable.xml` etc

**Comment by chnouman** [comment]
o let me try dear.

**Comment by chnouman** [comment]
thanks alot.
