### ISSUE TITLE
Change text of "more apps" card on the homescreen

### ISSUE THREAD

**Issue by mueller-ma** [danimahardhika/candybar-library#56]
Hi,
is it possible to change the text of the "more apps on playstore" card on the main screen? The url is "google_play_dev"

**Comment by danimahardhika** [comment]
At the moment no, but I think I got what you want. I'll add an option to show more apps, I mean like more more apps link press to install, on home.

**Comment by Technologx** [comment]
What would make this better and look better add this to the about area of the app and have a popup window with the list of apps you have a scrollable window. Maybe have this as a option to either be in the about area or the homescreen have it as a choice in the dashboard_configurations.xml.
