### ISSUE TITLE
My wallpaper JSON file is not supporting

### ISSUE THREAD

**Issue by AnkitRawat** [danimahardhika/candybar-library#57]
I hosted wallpapers on my other Github account and I am getting error "Unable to fetch data from server". I recently migrated from Polar dashboard to Candybar. I have also used Icon showcase dashboard earlier. Both dashboard supports my JSON file. 

URL of JSON file looks like this: 
https://raw.githubusercontent.com/xxxxxxxxx/Wallpapers/master/Wallpapers.json
Note- This URL won't load because I have replaced my username with "xxxxxxxxx".

Inside JSON File, I have a code like this.
```
{
  "wallpapers": [
    {
      "url": "https://raw.githubusercontent.com/xxxxxxxxx/Wallpapers/master/Wallpapers/Galaxy%20S8/Wallpaper%20(01).jpg",
      "dimensions": "2880x2560",
      "name": "Wallpaper 1",
      "copyright": "Copyright ¸ 2017 Samsung. All rights reserved.",
      "author": "Galaxy S8"
    },
```

**Comment by danimahardhika** [comment]
Your JSON format missed "thumbUrl", dimensions  and copyright is not needed. 

At the moment you need to follow JSON format from [here](https://github.com/danimahardhika/candybar-library/blob/master/json%20example/wallpaper_example.json).

The problem not comes from your JSON link.

**Comment by AnkitRawat** [comment]
I changed JSON array from "wallpapers" to "Wallpapers". Error is fixed now but wallpapers are still not showing up. My JSON file contains 1000+ wallpapers. I can't edit that file. Can adding some code, fetch "thumbUrl" from "url".

**Comment by danimahardhika** [comment]
Wait until next release in a few hours

**Comment by AnkitRawat** [comment]
Thank you so much! 💃

**Comment by danimahardhika** [comment]
@AnkitRawat Check release [**3.1.4**](https://github.com/danimahardhika/candybar-library/releases/tag/3.1.4), it should works.

**Comment by AnkitRawat** [comment]
Worked! Thanks! :D

**Comment by danimahardhika** [comment]
@AnkitRawat Do not use 3.1.4, use release [**3.1.5**](https://github.com/danimahardhika/candybar-library/releases/tag/3.1.5) instead

**Comment by AnkitRawat** [comment]
okay! Just now updated again! :D
