### ISSUE TITLE
[Request] Icon Request Feature

### ISSUE THREAD

**Issue by Technologx** [danimahardhika/candybar-library#59]
When it comes to icon requests is there anyway you can make it generate a appmap & theme_resources file as well? Because adding that info 1 by 1 takes to much time when it comes to creating icon packs. This would be greatly appreciated since some launchers use these like LG Home for example.

Here's a link to a good icon request tool: https://github.com/AllanWang/Icon-Request-Tool

**Comment by danimahardhika** [comment]
Check here https://github.com/danimahardhika/candybar-library/wiki/Dashboard-Configuration
