### ISSUE TITLE
Global Icon Search Layout Issue

### ISSUE THREAD

**Issue by fundoozzz** [danimahardhika/candybar-library#6]
After enabling global icon request, once you click on the search bar, it starts showing the list of icons alphabetically. But when the keyboard pops up at the same time, the icon list layout hides the search bar almost half.
![screenshot_2016-11-14-15-25-07](https://cloud.githubusercontent.com/assets/1597407/20260218/a8bc6aba-aa7e-11e6-89bc-42581d43f2fb.png)

**Comment by danimahardhika** [comment]
This is not serious issue, but I also find this is not looks good. Still can't find the solution for now.

**Comment by fundoozzz** [comment]
One more thing, shouldn't the suggestion start showing only after receiving any input?
It starts showing icon list even when you just click on the search bar without any text input.

**Comment by danimahardhika** [comment]
Fixed on release [1.2.0](https://github.com/danimahardhika/candybar-library/releases/tag/1.2.0)
