### ISSUE TITLE
exclude strings to strings.xml

### ISSUE THREAD

**Issue by mueller-ma** [danimahardhika/candybar-library#61]
And allow translations this way

**Comment by danimahardhika** [comment]
Translation site https://danimahardhika.oneskyapp.com/collaboration/project?id=245866

**Comment by msay2** [comment]
I can not connect.

How to create an account ?

(It is for the French language, there are some spelling mistakes).

**Comment by danimahardhika** [comment]
@msay2 You can login with github account

**Comment by msay2** [comment]
This is good, I just found the page to create an account 😉
