### ISSUE TITLE
What about translations?

### ISSUE THREAD

**Issue by Primokorn** [danimahardhika/candybar-library#65]
Hi,

I know it's pretty obvious to understand how to use the app as an user but soem folks would like to have translations.
Is it something already planned?
I could start translating **dashboard_strings.xml** to French, except if you want to manage them on Crowdin (or somewhere else).

Thank you.

**Comment by danimahardhika** [comment]
Translation site https://danimahardhika.oneskyapp.com/collaboration/project?id=245866
