### ISSUE TITLE
Allow certain strings to be excluded while displaying preview

### ISSUE THREAD

**Issue by fundoozzz** [danimahardhika/candybar-library#7]
I have icons named like apps_facebook, games_angry_birds, google_drive, misc_app_drawer.
It would be awesome if there can be a feature to add certain strings which will get excluded while displaying icon name such as if we put "apps_", "games_", "google_", "misc_" in that string array then the icon names will displayed as Facebook, Angry Birds, Drive & App Drawer capitalizing first alphabet of each word and underscore amounting to a space.

**Comment by danimahardhika** [comment]
Added in release [**1.0.8**](https://github.com/danimahardhika/candybar-library/releases/tag/1.0.8)
