### ISSUE TITLE
Wallpaper zoomed when applied using inbuilt apply

### ISSUE THREAD

**Issue by danimahardhika** [danimahardhika/candybar-library#70]

**Comment by randomvector** [comment]
Hi there,

How do I make the update to the candybar-sample-master. I'm using it for my icons and don't have see the WallpaperActivity or the Wallpaper Helper java. I am very new to Android Development so any help would be great.

**Comment by danimahardhika** [comment]
Read the [Wiki Site](https://github.com/danimahardhika/candybar-library/wiki), [How to Update](https://github.com/danimahardhika/candybar-library/wiki/How-to-Update).
