### ISSUE TITLE
Lambda expressions not supported

### ISSUE THREAD

**Issue by devesh796** [danimahardhika/candybar-library#71]
When i run the app in android studio i get this error : Lambda expressions are not supported at this language level. How do i get rid off this ? 

![lambda_expressions](https://user-images.githubusercontent.com/15872393/27790386-de0571c2-600d-11e7-91d5-5958d71198db.png)

**Comment by danimahardhika** [comment]
If you want to import the library to your project and modify it, as written [here](https://github.com/danimahardhika/candybar-library/wiki/Setup#requirements), you need Java SE Development Kit 8.

**But**, if you are trying to use CandyBar in your **Icon Pack**, you are importing wrong project. Read [Wiki Site](https://github.com/danimahardhika/candybar-library/wiki/Setup#1-download-sample-project) carefully. **"First you need to download sample project from here."** It's pointing to different project.
