### ISSUE TITLE
wallpapers_column_count is set to 1 helper text obscured

### ISSUE THREAD

**Issue by randomvector** [danimahardhika/candybar-library#72]
When the integer is set to 1 for wallpapers_column_count the wallpaper helper text on first load is obscured by the white circle animation:

![screenshot_20170703-204904](https://user-images.githubusercontent.com/27604724/27806344-f762880c-6031-11e7-961c-a0520e7202ae.png)

The above screenshot is of what is looks with this change:

`<integer name="wallpapers_column_count">1</integer>
`

**Comment by danimahardhika** [comment]
Because it's not designed that way. If you want to modify wallpaper column count you need to modify tap intro part too.

**Comment by randomvector** [comment]
Where is tap intro located (for reference)?

**Comment by danimahardhika** [comment]
TapIntroHelper.java, WallpapersFragment.java
