### ISSUE TITLE
How to mask the unthemed icons

### ISSUE THREAD

**Issue by abinashn1** [danimahardhika/candybar-library#73]
Is it possible to mask the icon of those apps which are not themed in the icon pack. Please provide some hint or guide on how can I do that.

**Comment by danimahardhika** [comment]
Yes, it's possible. Check [this sample appfilter](https://github.com/Cordazar/iconpack_template/blob/master/assets/appfilter.xml).

Already wrote about this in font page.
**NOTE: This is just Icon Pack Dashboard, not Icon Pack template or Icon Pack tutorial. You need to add required XML for Icon Pack by yourself.**

If you want to ask something related to the icon pack, better ask it on Google+ community.
