### ISSUE TITLE
Wallpaper: Pick an image from Nova Launcher

### ISSUE THREAD

**Issue by Primokorn** [danimahardhika/candybar-library#75]
Hi,

1. From Nova Launcher (and probably others) long press an empty area on the homescreen
2. Select **Wallpapers**
3. Select **Apps & Themes**
4. My icon packs should be available here but there's nothing.

Thank you.

I'm on CandyBar 3.2.0.

**Comment by danimahardhika** [comment]
It's conflict with image picker, this won't works unless image picker feature removed.
