### ISSUE TITLE
Muzai setting not appearing after clicking icon and more

### ISSUE THREAD

**Issue by irshad2809** [danimahardhika/candybar-library#77]
![screenshot_20170723-181129](https://user-images.githubusercontent.com/18377546/28499408-bee11e20-6fd2-11e7-96d8-f84ceac0c28b.png)
Clicking settings icon does nothing , am I missing something here , 

2) is user prompted for rating automatically ? 
3) is  user prompted for donations automatically ? 
4)  is it possible to add options to automatically change wallpapers after some provided time period 
 ?

**Comment by danimahardhika** [comment]
Make sure to setup correctly https://github.com/danimahardhika/candybar-library/wiki/Setup#open-androidmanifestxml

2 3 No
4. That's what muzei do

**Comment by irshad2809** [comment]
is following senario possible :- user is allowed to request certain amount of icons for free and after that limit is reached then only show paid request options ?

**Comment by danimahardhika** [comment]
Read the wiki site https://github.com/danimahardhika/candybar-library/wiki/Customization:-Basic#icon-request
