### ISSUE TITLE
Image dimensions for theme_feature and theme_preview1

### ISSUE THREAD

**Issue by randomvector** [danimahardhika/candybar-library#78]
Do you have any suggestions for sizing (dimensions, ratio, etc.) for the theme_feature and theme_preview images? I am not really sure what to create for them (suggestions of what the images should contain for the end user)? as I don't use apex any help would be great. Also where should the images to placed in the res folder?

Thanks

**Comment by danimahardhika** [comment]
I'm not sure. Most themer using a device screenshot with icon pack applied.

**Comment by randomvector** [comment]
Thanks for the info
