### ISSUE TITLE
Dynamic Calendar Icons

### ISSUE THREAD

**Issue by Sylvia-Keren-Happuch** [danimahardhika/candybar-library#79]
How can I make dynamic calendar icons? For example, on August 1 there should be a 1, on August 2 there should be a 2, ... and on August 31 there should be a 31 (see pic).
![31](https://user-images.githubusercontent.com/28256260/28535449-c374ea52-70a4-11e7-91cf-162e8ff534f9.png)

**Comment by danimahardhika** [comment]
Name your calendar icon like this calendar_1, calendar_2, ..., calendar_31. See sample [appfilter.xml](https://github.com/danimahardhika/candybar-sample/blob/master/app/src/main/res/xml/appfilter.xml) for more info.
