### ISSUE TITLE
[Suggestion] Donation Card in Home Fragment

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#8]
Since i can't hack my way around the binding:

It would be nice to have an optional Card like "Quick apply" for Donations in the home fragment.
The xml was simple copy & change while i can't seem to find a good way to add the binding. Could you provide a public method or another noob-friendly way good sir?

Cheers, thank you and have a great Sunday!

**Comment by danimahardhika** [comment]
What for? Support development already included in navigation drawer.

**Comment by leifniem** [comment]
Keeping it free. People tend to donate little to nothing, but it got better when i included a donation button in the first view.

**Comment by danimahardhika** [comment]
If you want to modify the library you can modify it by yourself. I think donation options shouldn't placed inside home. I'm not planning to move it, and I don't want to add unnecessary option. Too many options can impact dashboard performance. Sorry.

**Comment by leifniem** [comment]
I totally understand your point. Still a big thank you for such a great dashboard :)
