### ISSUE TITLE
[Request] Open app in playstore on clicking icon in preview

### ISSUE THREAD

**Issue by themezilla02** [danimahardhika/candybar-library#86]
![screenshot_20170820-183218](https://user-images.githubusercontent.com/12219459/29504147-19269a60-865b-11e7-9f4a-c6a2c747c2d1.png)

This is a feature request. Like in the screenshot above, will it be possible that when the user touches the icon in the preview section, it opens the app page on playstore?
Thanks

**Comment by danimahardhika** [comment]
What if the icon used by more than 1 activity? What if the app not available on Google play?

**Comment by themezilla02** [comment]
If the app is not available on play store, it will simply show that the app is not available in the playstore window.
The only issue is that if the icon is used by more than one activity. In that case, may be we can give the user a choice which activity link to open?

**Comment by randomvector** [comment]
This can add a lot of confusion to the user as a lot of apps have many activities. For instance Whatsapp has over 25 activities. Textra has over 50 activities! This is very user unfriendly especially those without with little or no technical knowledge. Also many apps are not on the Play Store (mostly system apps but many others too)

A suggestion might be something like having a share menu (top right of icon preview) so you can use a search string for the app on the web. (I did a quick mock up below)

Example:

When thew user clicks on the share menu it would search the AppName + "android app" in the users chosen browser.

Search string example for browser

"Whatsapp android app"
"Instagram android app"
"Chrome android app"
 
I must point out that from a user experience this is very disruptive as the user will be taken away from the icon pack app each time the user touches the icon. Would be quite frustrating from users point of view.

![29504147-19269a60-865b-11e7-9f4a-c6a2c747c2d1](https://user-images.githubusercontent.com/27604724/29781542-6b4d8ff4-8c11-11e7-9137-dfbbdc18e6de.jpg)

**Comment by danimahardhika** [comment]
I won't add this
