### ISSUE TITLE
Icons doesn't apply to the launcher

### ISSUE THREAD

**Issue by AlessandroCasnigo** [danimahardhika/candybar-library#88]
Hello, I do 20+ icons and i named some with the app name, I applied the icons but nothing happened. I use Nova Launcher.

**Comment by randomvector** [comment]
Have you made an appfilter (appfilter.xml)?

You need an appfilter to match the app activities to the correct icon.

**Comment by AlessandroCasnigo** [comment]
No, i don't, how I modify the `appfilter.xml` in the `xml` folder to make coincide icon and process?

Thanks for helping me 😄

**Comment by danimahardhika** [comment]
You need to make appfilter.xml first.

As I said on main page, "This is not icon pack tutorial or icon pack template .........", this is just the dashboard.

Your question above, it's the same as asking "how to create an icon pack", and you are asking in wrong place. Join Google+ community and ask there.

**Comment by randomvector** [comment]
Please look at the example appfilter that's included in the Candybar Sample master (it's in the CandyBar wiki).

**The Appfilter is very important to match your icons to the right apps**

Here's an example for matching Facebook app matching to the facebook icon (facebook.png)

`<item component="ComponentInfo{com.facebook.katana/com.facebook.katana.LoginActivity}" drawable="facebook" />`

The first part helps identify the Facebook App Activity:

item component="ComponentInfo{com.facebook.katana/com.facebook.katana.LoginActivity}" 

The second part tells what icon (without the png extension) to match to the activity:

drawable="facebook"

Your appfilter should use this each and every app you want to match to icons

`<item component="ComponentInfo{App Activity}" drawable="Icon Name without extension" />`

Many apps have multiple activities but you can link multiple activities to the same icons.
Example below for Textra:

```
<item component="ComponentInfo{com.textra/com.mplus.lib.ui.main.Main}" drawable="textrasms" />

<item component="ComponentInfo{com.textra/com.mplus.lib.Main_ff90a6ae}" drawable="textrasms" />

<item component="ComponentInfo{com.textra/com.mplus.lib.Main_ff03a8f9}" drawable="textrasms" />


```
Hope this helps!

**Look at the candybar sample it's really helpful.**

**Comment by AlessandroCasnigo** [comment]
Where I see the app activity?

**Comment by randomvector** [comment]
You can see them from Nova Launcher (you must enable labs mode- search on google "labs/debug mode Nova Launcher").

This is a lot to ask for on a Github issue. Check out the Google+ community as Dani suggested.

I had no one tell me how to do this and I have very little coding experience. I just did the research myself and only post stuff on Github when I had issues/errors with the dashboard in Android Studio. I'm not trying to be rude but the questions you've been asking, is basic information you should know when making an icon pack. Don't be discouraged we all started somewhere!

Making the icons is relevantly easy but making them work with the icon dashboard is hard. You should do more research into how icon packs work on android. 

**Look at the Candybar Sample it really helped me understand the structure of the icon dashboard and what needs to be included to make a icon pack.**

**Comment by AlessandroCasnigo** [comment]
thx dude 😄
