### ISSUE TITLE
[Suggestion] Check for IAP bypassers.

### ISSUE THREAD

**Issue by leifniem** [danimahardhika/candybar-library#9]
Got 3 premium requests which weren't paid for, so i downloaded to see if freedom is able to bypass the IAP process and it is.

Just a suggestion to check for the packages via License Check.

Sorry if i'm bothering you with such exotic problems Dani.

**Comment by fundoozzz** [comment]
I second this issue. Even I have been getting over 10 premium requests daily by cracking in app purchase. I just verify the order number to check the validity of the purchase. It would be great if the in app purchases could no be cracked this easily using Freedom or Lucky Patcher

**Comment by danimahardhika** [comment]
I'm still working on it

**Comment by danimahardhika** [comment]
@leifniem Could you please contact me via hangouts, I need your help to do some testing

**Comment by danimahardhika** [comment]
@fundoozzz @leifniem As I'm searching, sadly there's no way to avoid this. But I'll keep the issue open, probably there will be a solution in future.

**Comment by leifniem** [comment]
Well manually checking back with received payments and assuming if they’re
legitimate it is then.
Anyway, a really big thank you for your efforts and fantastic work!

**Comment by fundoozzz** [comment]
@danimahardhika  How about disabling Premium Icon request if lucky patcher or Freedom apps are found installed on device?

**Comment by bil-elmoussaoui** [comment]
@fundoozzz you still can buy an application and install lucky patcher to disable ads or something else ;)

**Comment by fundoozzz** [comment]
@bil-elmoussaoui In most of the cases, these two apps, lucky patcher and freedom are used to crack in app purchases. For ad-blocking, people use apps like adfree which blocks ads system wide. Disabling Premium icon request won't affect the user experience in such cases and the genuine buyers will ultimately contact the developer in rare case where they are using these apps and want to make a purchase.

**Comment by danimahardhika** [comment]
@fundoozzz We can't judge every user has lucky patcher or freedom installed will buy fake premium request. But maybe this is the best option for now, it will be helpful if you can provide package name for lucky patcher and freedom.

**Comment by fundoozzz** [comment]
@danimahardhika Yes I agree, but it seems to be the best possible solution for now.
Here are the package names i found in the icon requests

**Lucky Patcher**
com.chelpus.lackypatch
com.dimonvideo.luckypatcher
com.forpda.lp
com.android.protips
com.android.vending.billing.InAppBillingService.LUCK
com.android.vending.billing.InAppBillingService.LOCK

**Freedom**
cc.madkite.freedom

**Comment by danimahardhika** [comment]
I think [this](https://github.com/danimahardhika/candybar-library/commit/c8e3650000e1e9aec63e3ee9ccf7436e1e2e8fde) is enough
