### ISSUE TITLE
Failed to resolve TapTargetView

### ISSUE THREAD

**Issue by dalight13** [danimahardhika/candybar-library#91]
Error:Failed to resolve: com.github.KeepSafe:TapTargetView:-SNAPSHOT

All my packs started showing this error today and I have no idea how to fix it. But from what I can see it is called from the library itself and not from the pack..

Any chance you know what I'm doing wrong?

Thanks

daLight

**Comment by tfarina223** [comment]
I have the same problem, haven't figured it out yet.

**Comment by danimahardhika** [comment]
Just try to do a gradle sync with internet on, then run or build signed apk.

**Comment by tfarina223** [comment]
Hey, that didn't work for me; it fails to sync Gradle and I still get that error. I'm not sure what's going on.

Thanks for your help

**Comment by danimahardhika** [comment]
This is not related with the library, probably Android Studio didn't compile the project correctly. Try to clean the dependencies.

1. Make sure you have internet connection
2. Take a look on bottom left of Android Studio, open **Terminal**
<p align="center"><img src="https://drive.google.com/uc?id=0B0f4ypHfNKm5N1JGbDl4WGk5eEE" width="680" align="middle"/></p>

3. Type **gradlew --refresh -dependencies**, then enter
4. Wait until it finish
5. Sync project with gradle files, wait until finish
6. Run the app or build signed apk

**Comment by tfarina223** [comment]
Thank you for the quick and informative response. Unfortunately it didn't work for me. I'm fairly new to this, so I'm not sure what's going on with it.

---

File C:\Users\xxx\.android\repositories.cfg could not be loaded.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.KeepSafe:TapTargetView:-SNAPSHOT.
     Required by:
         project :app > com.github.danimahardhika.candybar-library:core:-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by danimahardhika** [comment]
Which release of candybar are you using?

**Comment by tfarina223** [comment]
3.3.2, from candybar-sample

**Comment by danimahardhika** [comment]
@tfarina223 Just tried to import sample project, it's working just fine on my side. I'm pretty sure it's Android Studio problem, it seems like Android Studio didn't compile the project correctly. 

1. Try to restart your Android Studio, close then open again.
2. Make sure you have internet connection on
3. Do the step from post above

**EDIT:** Sorry it should be **gradlew --refresh-dependencies** not **gradlew --refresh -dependencies**. No space after "--refresh".

1. Take a look on bottom left of Android Studio, open **Terminal**
<p align="center"><img src="https://drive.google.com/uc?id=0B0f4ypHfNKm5N1JGbDl4WGk5eEE" width="680" align="middle"/></p>

3. Type **gradlew --refresh-dependencies**, then enter
4. Wait until finish

Make sure to wait until it finish, it will takes a while. After finished the terminal will shown a message like image below, then proceed to step 5.
<p align="center"><img src="https://drive.google.com/uc?id=0B0f4ypHfNKm5eDluMVhoalRXb1U" width="680" align="middle"/></p>

5. Sync project with gradle files, wait until finish
6. Run the app or build signed apk

**Comment by tfarina223** [comment]
Unfortunately it didn't work for me, I restarted Android Studio and my PC to be sure and I don't see what you showed in the second screenshot, it continues to show the error message I mentioned before.

**Comment by dalight13** [comment]
Terminal instructions give me the same thing... so weird...

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.KeepSafe:TapTargetView:-SNAPSHOT.
     Required by:
         project :app > com.github.danimahardhika.candybar-library:core:3.3.2

**Comment by dalight13** [comment]
I also get this warning when doing the refresh : 

NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to D:\Users\****\AppData\Local\Android\sdk1\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

**Comment by Seledity** [comment]
I'm also getting the same error. Everything was working fine until now. There are no errors on my end. Seeing that there are more than a couple people having this issue, it's something to be looked into. 
<img width="1235" alt="screen shot 2017-09-12 at 7 23 54 pm" src="https://user-images.githubusercontent.com/17224834/30352786-07b38292-97f0-11e7-86ce-e596836e39a5.png">

**Comment by danimahardhika** [comment]
@Seledity @dalight13 @tfarina223 Try release 3.3.3

**Comment by tfarina223** [comment]
Works for me, thanks a bunch!

**Comment by Seledity** [comment]
After updating to CandyBar 3.3.3, the issue has been resolved. Thanks!

**Comment by dalight13** [comment]
After updating to 3.3.3, everything is now resolved. Thank you very much!!!
