### ISSUE TITLE
[Issue]After the step"Open module:app build.gradle"

### ISSUE THREAD

**Issue by BasemAlMoudares** [danimahardhika/candybar-library#99]
and Changing applicationId "com.material.dashboard.candybar.sample" to my package name, i'm prompted"(1 too large file was ignored)", and the file location and name is "\build\generated\mockable-android-25.jar' (32 megabytes) is too large and cannot be scanned, what shall i do.

**Comment by danimahardhika** [comment]
Post the error message here

**Comment by BasemAlMoudares** [comment]
![first prompt after replace in path](https://user-images.githubusercontent.com/27851426/31305981-1157d710-ab57-11e7-9a53-4d8a902ff5da.PNG)
![second prompt after replace in path](https://user-images.githubusercontent.com/27851426/31305980-11515070-ab57-11e7-978d-095257127e7e.PNG)

**Comment by danimahardhika** [comment]
That's not an error
